<?php

namespace App\Enums;

enum AuditAction: string
{
    case LOGIN = 'LOGIN';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case LOGOUT = 'LOGOUT';
    case COURSE_CREATED = 'COURSE_CREATED';
    case COURSE_UPDATED = 'COURSE_UPDATED';
    case COURSE_ARCHIVED = 'COURSE_ARCHIVED';
    case COURSE_REQUEST_CREATED = 'COURSE_REQUEST_CREATED';
    case PAYMENT_PROOF_SUBMITTED = 'PAYMENT_PROOF_SUBMITTED';
    case PAYMENT_PROOF_APPROVED = 'PAYMENT_PROOF_APPROVED';
    case PAYMENT_PROOF_REJECTED = 'PAYMENT_PROOF_REJECTED';
    case PAYMENT_PROOF_DOWNLOADED = 'PAYMENT_PROOF_DOWNLOADED';
    case COURSE_REQUEST_APPROVED = 'COURSE_REQUEST_APPROVED';
    case COURSE_REQUEST_REJECTED = 'COURSE_REQUEST_REJECTED';
    case TELEGRAM_CHANNEL_CREATED = 'TELEGRAM_CHANNEL_CREATED';
    case TELEGRAM_CHANNEL_UPDATED = 'TELEGRAM_CHANNEL_UPDATED';
    case TELEGRAM_CHANNEL_DEACTIVATED = 'TELEGRAM_CHANNEL_DEACTIVATED';
    case MANUAL_TELEGRAM_ACCESS_PENDING = 'MANUAL_TELEGRAM_ACCESS_PENDING';
    case MANUAL_TELEGRAM_ACCESS_GRANTED = 'MANUAL_TELEGRAM_ACCESS_GRANTED';
    case TELEGRAM_ACCESS_REVOKED = 'TELEGRAM_ACCESS_REVOKED';
    case ADMIN_USER_CREATED = 'ADMIN_USER_CREATED';
    case ADMIN_USER_UPDATED = 'ADMIN_USER_UPDATED';
    case INSTRUCTOR_CREATED = 'INSTRUCTOR_CREATED';
    case INSTRUCTOR_UPDATED = 'INSTRUCTOR_UPDATED';
    case INSTRUCTOR_APPROVED = 'INSTRUCTOR_APPROVED';
    case INSTRUCTOR_REJECTED = 'INSTRUCTOR_REJECTED';
    case CATEGORY_CREATED = 'CATEGORY_CREATED';
    case CATEGORY_UPDATED = 'CATEGORY_UPDATED';
    case PASSWORD_RESET = 'PASSWORD_RESET';
    case PASSKEY_REGISTERED = 'PASSKEY_REGISTERED';
    case PASSKEY_REVOKED = 'PASSKEY_REVOKED';
}
